import { Item, ItemType, RarityType, EquipSlot } from '../models/items';

export const ACCESSORY_ITEMS: Item[] = [
  {
    id: 'amulet-epic',
    name: 'Epic Amulet',
    description: 'This ancient amulet has already saved several lives...',
    type: ItemType.Accessory,
    icon: 'assets/items/accessories/amulet-epic.png',
    baseValue: 750,
    equipSlot: [EquipSlot.Accessory1, EquipSlot.Accessory2],
    rarity: RarityType.Epic,
    subtype: 'amulet',
    effects: [{stat: 'maxHp', value: 10}]
  },
  {
    id: 'charm-wild',
    name: 'Charm of the Wild',
    description: 'Smells faintly of moss and rain. Grants a deep calm.',
    type: ItemType.Accessory,
    icon: 'assets/items/accessories/charm-wild.png',
    baseValue: 480,
    rarity: RarityType.Rare,
    subtype: 'amulet',
    equipSlot: [EquipSlot.Accessory1, EquipSlot.Accessory2],
    effects: [{ stat: 'maxHp', value: 5 }, { stat: 'resist', value: 1 }],
  },
  {
    id: 'chalice-shadows',
    name: 'Chalice of Shadows',
    description: 'Forged in the crypts of a forgotten empire, this chalice is only filled with the fall of a soul.',
    type: ItemType.Accessory,
    icon: 'assets/items/accessories/chalice-of-shadows.png',
    baseValue: 2000,
    rarity: RarityType.Artefact,
    subtype: 'generic',
    equipSlot: [EquipSlot.Accessory1, EquipSlot.Accessory2],
    effects: [{stat: 'maxMp', value: 20}]
  },
  {
    id: 'magic-tome',
    name: 'Magic Tome',
    description: 'A tome of magic, certainly some spells to learn in there.',
    type: ItemType.Accessory,
    icon: 'assets/items/accessories/magic-tome.png',
    baseValue: 300,
    equipSlot: [EquipSlot.Accessory1, EquipSlot.Accessory2],
    rarity: RarityType.Rare,
    subtype: 'book',
    effects: [{stat: 'maxMp', value: 5}]
  },
  {
    id: 'magic-tome-epic',
    name: 'Epic Grimoire',
    description: 'A grimoire not to be put in everyone\'s hands. Luckily, it\'s in yours.',
    type: ItemType.Accessory,
    icon: 'assets/items/accessories/magic-tome-epic.png',
    baseValue: 750,
    equipSlot: [EquipSlot.Accessory1, EquipSlot.Accessory2],
    rarity: RarityType.Epic,
    subtype: 'book',
    effects: [{stat: 'maxMp', value: 20}]
  },
  {
    id: 'medallion-destiny',
    name: 'Destiny Medallion',
    description: 'The Medallion of Destiny allows you to find your way even in the most twisted labyrinths!',
    type: ItemType.Accessory,
    icon: 'assets/items/accessories/medallion-destiny.png',
    baseValue: 1310,
    equipSlot: [EquipSlot.Accessory1, EquipSlot.Accessory2],
    rarity: RarityType.Legendary,
    subtype: 'book',
    effects: [{stat: 'mv', value: 1}, {stat: 'defense', value: 2}]
  },
  {
    id: 'orb-epic',
    name: 'A Mysterious Orb',
    description: 'A glowing shard from the Bestial Orb.',
    type: ItemType.Accessory,
    icon: 'assets/items/accessories/orb-epic.png',
    baseValue: 825,
    equipSlot: [EquipSlot.Accessory1, EquipSlot.Accessory2],
    effects: [{ stat: 'orbs.bestial', value: 1 }],
    rarity: RarityType.Epic,
    subtype: 'amulet'
  },
  {
    id: 'pendant-epic',
    name: 'Ancient Pendant',
    description: 'An antique pendant... the pieces seem to want to stay together despite their condition.',
    type: ItemType.Accessory,
    icon: 'assets/items/accessories/pendant-epic.png',
    baseValue: 825,
    equipSlot: [EquipSlot.Accessory1, EquipSlot.Accessory2],
    effects: [{ stat: 'orbs.elemental', value: 1 }],
    rarity: RarityType.Epic,
    subtype: 'amulet'
  },
  {
    id: 'ring-red',
    name: 'A Red Ring',
    description: 'A beautiful ring set with a glowing stone.',
    type: ItemType.Accessory,
    icon: 'assets/items/accessories/ring-red.png',
    baseValue: 100,
    equipSlot: [EquipSlot.Accessory1, EquipSlot.Accessory2],
    rarity: RarityType.Normal,
    effects: [{stat: 'maxHp', value: 1}]
  },
  {
    id: 'ring-blue',
    name: 'A Blue Ring',
    description: 'The blue stone set in this ring gives a beautiful effect.',
    type: ItemType.Accessory,
    icon: 'assets/items/accessories/ring-blue.png',
    baseValue: 100,
    equipSlot: [EquipSlot.Accessory1, EquipSlot.Accessory2],
    rarity: RarityType.Normal,
    effects: [{stat: 'maxMp', value: 1}]
  },
  {
    id: 'ring-queen',
    name: 'The Queen\'s Ring',
    description: 'The Queen\'s Ring is a ring forged in the ancient Great Royal Forge. It is indestructible.',
    type: ItemType.Accessory,
    icon: 'assets/items/accessories/ring-queen.png',
    baseValue: 1030,
    rarity: RarityType.Legendary,
    subtype: 'ring',
    equipSlot: [EquipSlot.Accessory1, EquipSlot.Accessory2],
    effects: [{ stat: 'maxHp', value: 10 }, { stat: 'attack', value: 2 }],
  },
  {
    id: 'ring-sparks',
    name: 'Ring of Sparks',
    description: 'A faint spark dances within the gem.',
    type: ItemType.Accessory,
    icon: 'assets/items/accessories/ring-sparks.png',
    baseValue: 465,
    rarity: RarityType.Rare,
    subtype: 'ring',
    equipSlot: [EquipSlot.Accessory1, EquipSlot.Accessory2],
    effects: [{ stat: 'maxMp', value: 5 }, { stat: 'attack', value: 1 }],
  },
  {
    id: 'tab-epic',
    name: 'Ancient Tabler',
    description: 'A tablet from ancient times. It certainly served a deity at one time...',
    type: ItemType.Accessory,
    icon: 'assets/items/accessories/tab-epic.png',
    baseValue: 750,
    equipSlot: [EquipSlot.Accessory1, EquipSlot.Accessory2],
    rarity: RarityType.Epic,
    effects: [{stat: 'orbs.natural', value: 1}]
  },
];

export const ARMOR_ITEMS: Item[] = [
  {
    id: 'armor-chainmail-power',
    name: 'Power Chainmail Armor',
    description: 'A chainmail-like armor that seems invincible and unalterable.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/armor-chainmail-power.png',
    baseValue: 800,
    equipSlot: [EquipSlot.Torso],
    rarity: RarityType.Legendary,
    effects: [{stat: 'defense', value: 5}]
  },
  {
    id: 'armor-leather',
    name: 'Leather Armor',
    description: 'Light armor, offers minimal protection but keeps mobility.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/armor-leather.png',
    baseValue: 120,
    equipSlot: [EquipSlot.Torso],
    rarity: RarityType.Normal,
    effects: [{stat: 'defense', value: 2}]
  },
  {
    id: 'armor-leather-mechanic',
    name: 'Mechanical Armor',
    description: 'This armor is lightweight and seems to completely conform to the shape of your body.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/armor-leather-mchanic.png',
    baseValue: 240,
    equipSlot: [EquipSlot.Torso],
    rarity: RarityType.Rare,
    effects: [{stat: 'defense', value: 3}]
  },
  {
    id: 'armor-iron',
    name: 'Iron Armor',
    description: 'Iron armor, heavy certainly, but perfect for protecting yourself against bad blows!',
    type: ItemType.Armor,
    icon: 'assets/items/armors/armor-iron.png',
    baseValue: 250,
    equipSlot: [EquipSlot.Torso],
    rarity: RarityType.Normal,
    effects: [{stat: 'defense', value: 4}]
  },
  {
    id: 'armor-iron-mechanic',
    name: 'Mechanical Iron Armor',
    description: 'This mechanical iron armor comes from an ancient time and a forgotten technology.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/armor-iron-mechanic.png',
    baseValue: 300,
    equipSlot: [EquipSlot.Torso],
    rarity: RarityType.Rare,
    effects: [{stat: 'defense', value: 4}]
  },
  {
    id: 'boots-dragon',
    name: 'Dragon Scale Boots',
    description: 'These boots made of dragon scales will never wear out, no matter the distance.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/boots-dragon.png',
    baseValue: 120,
    equipSlot: [EquipSlot.Feet],
    rarity: RarityType.Rare,
    effects: [{stat: 'flee', value: 3}]
  },
  {
    id: 'boots-mechanic',
    name: 'Mechanical Boots',
    description: 'These boots are beautiful, you almost feel like you are floating when you walk in them.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/boots-travel.png',
    baseValue: 80,
    equipSlot: [EquipSlot.Feet],
    rarity: RarityType.Rare,
    effects: [{stat: 'flee', value: 1}]
  },
  {
    id: 'boots-travel',
    name: 'Travel Boots',
    description: 'Good walking boots can make all the difference.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/boots-travel.png',
    baseValue: 40,
    equipSlot: [EquipSlot.Feet],
    rarity: RarityType.Normal,
    effects: [{stat: 'flee', value: 1}]
  },
  {
    id: 'gloves-leather',
    name: 'Leather Gloves',
    description: 'Well-made leather gloves. A little too big, but they\'re still comfortable.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/gloves-leather.png',
    baseValue: 60,
    equipSlot: [EquipSlot.Hand1],
    rarity: RarityType.Normal,
    effects: [{stat: 'attack', value: 1}]
  },
  {
    id: 'gloves-mechanic',
    name: 'Mechanical Gloves',
    description: 'These gloves are incredibly comfortable. They feel like they adjust themselves.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/gloves-mechanic.png',
    baseValue: 120,
    equipSlot: [EquipSlot.Hand1],
    rarity: RarityType.Rare,
    effects: [{stat: 'tool', value: 1}]
  },
  {
    id: 'gloves-shadow',
    name: 'Shadow Gloves',
    description: 'Shadow gloves. Apparently you can steal anything with them, even in broad daylight.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/gloves-shadow.png',
    baseValue: 460,
    equipSlot: [EquipSlot.Hand1],
    rarity: RarityType.Legendary,
    effects: [{stat: 'defense', value: 2}]
  },
  {
    id: 'helmet-echo',
    name: 'Helm of Echoes',
    description: 'When worn, faint voices murmur warnings before danger strikes.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/helmet-echo.png',
    baseValue: 475,
    rarity: RarityType.Rare,
    subtype: 'helmet',
    equipSlot: [EquipSlot.Head],
    effects: [{stat: 'defense', value: 2}, { stat: 'perception', value: 1 }],
  },
  {
    id: 'helmet-epic',
    name: 'Dragon Helmet',
    description: 'A dragon helmet, straight from the ancient forges. It\'s an honor to be able to wear it.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/helmet-epic.png',
    baseValue: 750,
    equipSlot: [EquipSlot.Head],
    rarity: RarityType.Epic,
    effects: [{stat: 'orbs.bestial', value: 2}]
  },
  {
    id: 'helmet-leather',
    name: 'Leather Helmet',
    description: 'A finely fitted leather helmet. It doesn\'t obstruct your vision and provides minimal protection.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/helmet-leather.png',
    baseValue: 70,
    equipSlot: [EquipSlot.Head],
    rarity: RarityType.Normal,
    effects: [{stat: 'defense', value: 1}]
  },
  {
    id: 'helmet-mechanic',
    name: 'Mechanical Helmet',
    description: 'You might think this helmet would hinder your vision, but it doesn\'t!',
    type: ItemType.Armor,
    icon: 'assets/items/armors/helmet-leather-mechanic.png',
    baseValue: 130,
    equipSlot: [EquipSlot.Head],
    rarity: RarityType.Rare,
    effects: [{stat: 'defense', value: 1}]
  },
  {
    id: 'helmet-luminous',
    name: 'Luminous Helmet',
    description: 'This luminous helmet exudes magic and seems indestructible.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/helmet-luminous.png',
    baseValue: 160,
    equipSlot: [EquipSlot.Head],
    rarity: RarityType.Rare,
    effects: [{stat: 'defense', value: 2}]
  },
  {
    id: 'helmet-iron-mechanic',
    name: 'Improved Mechanical Helmet',
    description: 'The first time you put on this helmet, you\'re a little confused. But then you can\'t live without it.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/helmet-iron-mechanic.png',
    baseValue: 130,
    equipSlot: [EquipSlot.Head],
    rarity: RarityType.Rare,
    effects: [{stat: 'defense', value: 1}]
  },
  {
    id: 'hat-magician',
    name: 'Wizard Hat',
    description: 'A crooked hat, allowing you to avoid being dazzled by the sun when casting a spell.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/hat-magician.png',
    baseValue: 60,
    equipSlot: [EquipSlot.Head],
    rarity: RarityType.Normal,
    effects: []
  },
  {
    id: 'hat-travel',
    name: 'Traveler\'s Hat',
    description: 'A simple traveler\'s hat. At least your head won\'t get cold!',
    type: ItemType.Armor,
    icon: 'assets/items/armors/hat-travel.png',
    baseValue: 30,
    equipSlot: [EquipSlot.Head],
    rarity: RarityType.Normal,
    effects: []
  },
  {
    id: 'mantle-travel',
    name: 'Traveler\'s Mantle',
    description: 'A cloak that always seems clean, no matter the mud.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/mantle-traveler.png',
    baseValue: 320,
    rarity: RarityType.Rare,
    subtype: 'robe',
    equipSlot: [EquipSlot.Torso],
    effects: [],
  },
  {
    id: 'outfit-common',
    name: 'Tunic',
    description: 'A common everyday tunic.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/outfit-travel.png',
    baseValue: 20,
    equipSlot: [EquipSlot.Torso],
    rarity: RarityType.Normal,
    effects: [],
  },
  {
    id: 'outfit-travel',
    name: 'Traveler\'s outfit',
    description: 'Simple yet comfortable, this outfit can last for years.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/outfit-travel.png',
    baseValue: 60,
    equipSlot: [EquipSlot.Torso],
    rarity: RarityType.Normal,
    effects: [{stat: 'maxHp', value: 1}],
  },
  {
    id: 'outfit-magician',
    name: 'Wizard Robe',
    description: 'Long robe and hood, nothing like it to keep your precious ingredients and parchments safe.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/outfit-magician.png',
    baseValue: 300,
    equipSlot: [EquipSlot.Torso],
    rarity: RarityType.Rare,
    effects: [{stat: 'maxHp', value: 5}, {stat: 'maxMp', value: 10} ],
  },
  {
    id: 'outfit-priest',
    name: 'Priest Robe',
    description: 'A priest\'s robe like those seen in churches. Let\'s pray that it brings you luck.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/outfit-priest.png',
    baseValue: 100,
    equipSlot: [EquipSlot.Torso],
    rarity: RarityType.Normal,
    effects: [{stat: 'maxHp', value: 2}],
  },
  {
    id: 'robe-archmage',
    name: 'Archmage Robe',
    description: 'The archmage robes are among the most beautiful creations of this kingdom.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/robe-archmage.png',
    baseValue: 1100,
    subtype: 'robe',
    equipSlot: [EquipSlot.Torso],
    rarity: RarityType.Legendary,
    effects: [{stat: 'maxHp', value: 5}, {stat: 'action', value: 1}],
  },
  {
    id: 'robe-darkness',
    name: 'Robe of Darkness',
    description: 'The Robe of Darkness, also known as the Robe of One, inspires fear simply by its presence.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/robe-darkness.png',
    baseValue: 2740,
    subtype: 'robe',
    equipSlot: [EquipSlot.Torso],
    rarity: RarityType.Artefact,
    effects: [{stat: 'fear', value: 1}, {stat: 'maxMp', value: 10}],
  },
  {
    id: 'shield-mechanic-long',
    name: 'Long Mechanical Shield',
    description: 'This ancient shield still seems to work, at least it makes noise.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/shield-mechanic-long.png',
    baseValue: 400,
    rarity: RarityType.Rare,
    subtype: 'shield',
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    effects: [{ stat: 'defense', value: 5 },],
  },
  {
    id: 'shield-mechanic-small',
    name: 'Mechanical Shield',
    description: 'This ancient shield still seems to work, or at least vibrates.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/shield-mechanic-small.png',
    baseValue: 300,
    rarity: RarityType.Rare,
    subtype: 'shield',
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    effects: [{ stat: 'defense', value: 2 }],
  },
  {
    id: 'shield-mirror',
    name: 'Mirror Shield',
    description: 'Its surface reflects not only faces… but intentions.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/shield-mirror.png',
    baseValue: 880,
    rarity: RarityType.Legendary,
    subtype: 'shield',
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    effects: [{ stat: 'defense', value: 1 }, { stat: 'reflect', value: 10, type: 'percent'}],
  },
  {
    id: 'shield-dragon',
    name: 'Dragon Shield',
    description: 'A shield in ancient Dragon Riders. It must have been amazing to fly on a dragon...',
    type: ItemType.Armor,
    icon: 'assets/items/armors/shield-dragon.png',
    baseValue: 650,
    rarity: RarityType.Epic,
    subtype: 'shield',
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    effects: [{ stat: 'defense', value: 3 }],
  },
  {
    id: 'shield-spirit',
    name: 'Spirit Shield',
    description: 'A shield of spirits, certainly linked to an element, but we still need to understand what is written there...',
    type: ItemType.Armor,
    icon: 'assets/items/armors/shield-spirit.png',
    baseValue: 500,
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    rarity: RarityType.Rare,
    effects: [{stat: 'maxMp', value: 5}, {stat: 'defense', value: 3}],
  },
  {
    id: 'shield-iron',
    name: 'Iron Shield',
    description: 'An iron shield, incredibly strong. With this in your hands, no one can touch you!',
    type: ItemType.Armor,
    icon: 'assets/items/armors/shield-iron.png',
    baseValue: 250,
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    rarity: RarityType.Normal,
    effects: [{stat: 'defense', value: 3}],
  },
  {
    id: 'shield-long',
    name: 'Long Shield',
    description: 'A long, somewhat bulky shield. However, it is very effective against archers or anything else that comes your way.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/shield-long.png',
    baseValue: 500,
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    rarity: RarityType.Rare,
    effects: [{stat: 'defense', value: 6}, {stat: 'attack', value: -3}],
  },
  {
    id: 'shield-runic',
    name: 'Runic Shield',
    description: 'The decorations engraved on this shield are simply magnificent and incredibly precise.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/shield-runic.png',
    baseValue: 750,
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    rarity: RarityType.Epic,
    effects: [{stat: 'defense', value: 3}, {stat: 'maxHp', value: 10}]
  },
  {
    id: 'shield-small',
    name: 'Small Shield',
    description: 'A small, round shield, light and handy. It can still last for years if taken care of.',
    type: ItemType.Armor,
    icon: 'assets/items/armors/shield-small.png',
    baseValue: 90,
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    rarity: RarityType.Normal,
    effects: [{stat: 'defense', value: 2}]
  },
];

export const CONSUMABLE_ITEMS: Item[] = [
  {
    id: 'apples',
    name: 'Apples',
    description: 'A few red apples, but not from a fairy tale!',
    type: ItemType.Consumable,
    icon: 'assets/items/consumables/apples.png',
    stackable: true,
    baseValue: 2,
    rarity: RarityType.Normal,
    effects: [{ stat: 'hp', value: 2 }]
  },
  {
    id: 'ammo-arrows',
    name: 'Arrows',
    description: 'Having a bow is good! With arrows it\'s even better.',
    type: ItemType.Consumable,
    icon: 'assets/items/consumables/ammo-arrows.png',
    stackable: true,
    baseValue: 5,
    rarity: RarityType.Normal,
    effects: []
  },
  {
    id: 'ammo-bolts',
    name: 'Bolts',
    description: 'These crossbow bolts whistle when fired.',
    type: ItemType.Consumable,
    icon: 'assets/items/consumables/ammo-bolts.png',
    stackable: true,
    baseValue: 5,
    rarity: RarityType.Normal,
    effects: []
  },
  {
    id: 'potion-heal-small',
    name: 'Minor Healing Potion',
    description: 'A reddish liquid that heals small wounds (+10 HP)',
    type: ItemType.Consumable,
    icon: 'assets/items/consumables/potion-heal-small.png',
    stackable: true,
    baseValue: 25,
    effects: [{ stat: 'hp', value: 10 }],
    rarity: RarityType.Normal
  },
  {
    id: 'potion-heal',
    name: 'Healing Potion',
    description: 'A reddish liquid that heals small wounds (+30 HP)',
    type: ItemType.Consumable,
    icon: 'assets/items/consumables/potion-heal.png',
    stackable: true,
    baseValue: 50,
    effects: [{ stat: 'hp', value: 30 }],
    rarity: RarityType.Normal
  },
  {
    id: 'potion-mana-small',
    name: 'Minor Mana Potion',
    description: 'A blue liquid that invigorates the magical flow a little (+10 MP)',
    type: ItemType.Consumable,
    icon: 'assets/items/consumables/potion-mana-small.png',
    stackable: true,
    baseValue: 35,
    effects: [{ stat: 'mp', value: 10 }],
    rarity: RarityType.Normal
  },
  {
    id: 'potion-mana',
    name: 'Mana Potion',
    description: 'A blue liquid that invigorates the magical flow (+30 MP)',
    type: ItemType.Consumable,
    icon: 'assets/items/consumables/potion-mana.png',
    stackable: true,
    baseValue: 60,
    effects: [{ stat: 'mp', value: 30 }],
    rarity: RarityType.Normal
  },
  {
    id: 'trap-mechanic',
    name: 'Simple Mechanical Trap',
    description: 'A rudimentary invention, still dangerous.',
    type: ItemType.Consumable,
    icon: 'assets/items/consumables/trap-mechanic.png',
    baseValue: 40,
    effects: [{ stat: 'damage', value: 10 }],
    rarity: RarityType.Normal
  },
  {
    id: 'travel-ration',
    name: 'Travel Ration',
    description: 'Not very fresh, but fills the stomach.',
    type: ItemType.Consumable,
    icon: 'assets/items/consumables/travel-ration.png',
    stackable: true,
    baseValue: 5,
    effects: [{ stat: 'hp', value: 3 }],
    rarity: RarityType.Normal
  },
];

export const RESOURCE_ITEMS: Item[] = [
  {
    id: 'bones',
    name: 'Bones',
    description: 'A pile of bones... of perhaps several creatures.',
    type: ItemType.Resource,
    icon: 'assets/items/resources/bones.png',
    stackable: true,
    baseValue: 5,
    rarity: RarityType.Normal,
    effects: []
  },
  {
    id: 'berries',
    name: 'Berries',
    description: 'Eating berries from time to time doesn\'t hurt.',
    type: ItemType.Resource,
    icon: 'assets/items/resources/berries.png',
    stackable: true,
    baseValue: 10,
    rarity: RarityType.Normal,
    effects: []
  },
  {
    id: 'wheat',
    name: 'Wheat',
    description: 'With wheat we make bread, bread is the basis!',
    type: ItemType.Resource,
    icon: 'assets/items/resources/wheat.png',
    stackable: true,
    baseValue: 5,
    rarity: RarityType.Normal,
    effects: []
  },
  {
    id: 'coal',
    name: 'Coal',
    description: 'Coal... your hands are all black now!',
    type: ItemType.Resource,
    icon: 'assets/items/resources/coal.png',
    stackable: true,
    baseValue: 10,
    rarity: RarityType.Normal,
    effects: []
  },
  {
    id: 'fibers',
    name: 'Fibers',
    description: 'You might not be able to make a rope out of it, but it can still be useful.',
    type: ItemType.Resource,
    icon: 'assets/items/resources/fibers.png',
    stackable: true,
    baseValue: 10,
    rarity: RarityType.Normal,
    effects: []
  },
  {
    id: 'herbs',
    name: 'Compound Herbs',
    description: 'Different dried plants with diverse and varied capacities.',
    type: ItemType.Resource,
    icon: 'assets/items/resources/herbs.png',
    stackable: true,
    baseValue: 10,
    rarity: RarityType.Normal,
    effects: []
  },
  {
    id: 'iron',
    name: 'Iron',
    description: 'Iron is heavy, but if you melt it down, you can make something solid out of it.',
    type: ItemType.Resource,
    icon: 'assets/items/resources/iron.png',
    stackable: true,
    baseValue: 15,
    rarity: RarityType.Normal,
    effects: []
  },
  {
    id: 'leather',
    name: 'Leather',
    description: 'Leather! We need to tan it, wash it, and see what we can create with it?',
    type: ItemType.Resource,
    icon: 'assets/items/resources/leather.png',
    stackable: true,
    baseValue: 15,
    rarity: RarityType.Normal,
    effects: []
  },
  {
    id: 'oil',
    name: 'Oil',
    description: 'Oil can be used for so many things. It\'s best to keep it somewhere.',
    type: ItemType.Resource,
    icon: 'assets/items/resources/oil.png',
    stackable: true,
    baseValue: 15,
    rarity: RarityType.Normal,
    effects: []
  },
  {
    id: 'sand',
    name: 'Sand',
    description: 'The problem with sand is that it gets everywhere. But hey, there\'s nothing stopping you from keeping a handful.',
    type: ItemType.Resource,
    icon: 'assets/items/resources/sand.png',
    stackable: true,
    baseValue: 5,
    rarity: RarityType.Normal,
    effects: []
  },
  {
    id: 'scrap',
    name: 'Scrap',
    description: 'Scrap metal. The trick is figuring out how to put it all together.',
    type: ItemType.Resource,
    icon: 'assets/items/resources/scrap.png',
    stackable: true,
    baseValue: 8,
    rarity: RarityType.Rare,
    effects: []
  },
  {
    id: 'stone',
    name: 'Stones',
    description: 'Stones, stones, they weigh their weight after a while...',
    type: ItemType.Resource,
    icon: 'assets/items/resources/stone.png',
    stackable: true,
    baseValue: 10,
    rarity: RarityType.Normal,
    effects: []
  },
  {
    id: 'water',
    name: 'Water',
    description: 'Not sure if we can drink this water, but it will be useful anyway.',
    type: ItemType.Resource,
    icon: 'assets/items/resources/water.png',
    stackable: true,
    baseValue: 5,
    rarity: RarityType.Normal,
    effects: []
  },
  {
    id: 'wood',
    name: 'Wood',
    description: 'Wood is an essential resource, you must always have some in stock.',
    type: ItemType.Resource,
    icon: 'assets/items/resources/wood.png',
    stackable: true,
    baseValue: 10,
    rarity: RarityType.Normal,
    effects: []
  },
  {
    id: 'dark-wood',
    name: 'Wood',
    description: 'Dark wood can be used for many things, but you still need to know its effects.',
    type: ItemType.Resource,
    icon: 'assets/items/resources/wood-dark.png',
    stackable: true,
    baseValue: 14,
    rarity: RarityType.Normal,
    effects: []
  },
  {
    id: 'sacred-wood',
    name: 'Sacred Wood',
    description: 'Sacred wood... Used well, it can work miracles.',
    type: ItemType.Resource,
    icon: 'assets/items/resources/wood-sacred.png',
    stackable: true,
    baseValue: 50,
    rarity: RarityType.Rare,
    effects: []
  },
  {
    id: 'crystal',
    name: 'Crystal',
    description: 'This crystal emanates magic, it is at the same time fascinating and frightening.',
    type: ItemType.Resource,
    icon: 'assets/items/resources/crystal.png',
    stackable: true,
    baseValue: 50,
    rarity: RarityType.Rare,
    effects: []
  },
  {
    id: 'gem',
    name: 'Gem',
    description: 'A gem that is still raw. It will need to be cut with precision.',
    type: ItemType.Resource,
    icon: 'assets/items/resources/gem.png',
    stackable: true,
    baseValue: 40,
    rarity: RarityType.Rare,
    effects: []
  },
  {
    id: 'soul-stone',
    name: 'Soul Stone',
    description: 'A Soul Stone as the ancients said... What was its origin?',
    type: ItemType.Resource,
    icon: 'assets/items/resources/stone-soul.png',
    stackable: true,
    baseValue: 50,
    rarity: RarityType.Rare,
    effects: []
  },
  {
    id: 'magic-dust',
    name: 'Magic Dust',
    description: 'This powder makes children very happy. If only they knew...',
    type: ItemType.Resource,
    icon: 'assets/items/resources/dust-magic.png',
    stackable: true,
    baseValue: 20,
    rarity: RarityType.Normal,
    effects: []
  },
];

export const UTILITY_ITEMS: Item[] = [
  {
    id: 'axe-lumberjack',
    name: 'Lumberjac\'s Axe',
    description: 'It\'s still more practical for cutting wood!',
    type: ItemType.Utility,
    icon: 'assets/items/utility/axe-lumberjack.png',
    baseValue: 60,
    effects: [],
    rarity: RarityType.Normal
  },
  {
    id: 'key-iron',
    name: 'Iron Key',
    description: 'A simple iron key, which must certainly open something... but what?',
    type: ItemType.Utility,
    icon: 'assets/items/utility/key-iron.png',
    baseValue: 20,
    effects: [{ stat: 'open', value: 1 }],
    rarity: RarityType.Normal
  },
  {
    id: 'tools',
    name: 'Tool Set',
    description: 'You should always have some tools on hand. Even in a cell, they\'re useful.',
    type: ItemType.Utility,
    icon: 'assets/items/utility/tools.png',
    effects: [{ stat: 'tool', value: 1 }],
    baseValue: 25,
    rarity: RarityType.Normal
  },
  {
    id: 'pickaxe',
    name: 'Pickaxe',
    description: 'A pickaxe, as the old man used to say, always lets you find things!',
    type: ItemType.Utility,
    icon: 'assets/items/utility/pickaxe.png',
    baseValue: 60,
    effects: [],
    rarity: RarityType.Normal
  },
  {
    id: 'sickle',
    name: 'Sickle',
    description: 'We don\'t know, we might need to harvest some herbs.',
    type: ItemType.Utility,
    icon: 'assets/items/utility/sickle.png',
    effects: [{ stat: 'tool', value: 1 }],
    baseValue: 50,
    rarity: RarityType.Normal
  },
  {
    id: 'torch',
    name: 'Torch',
    description: 'Provides light in dark areas. And there are dark areas everywhere!',
    type: ItemType.Utility,
    icon: 'assets/items/utility/torch.png',
    baseValue: 10,
    effects: [{ stat: 'light', value: 1 }],
    rarity: RarityType.Normal
  },
];

export const WEAPON_MELEE_ITEMS: Item[] = [
  // WEAPON MELEE
  {
    id: 'axe-wanderer',
    name: 'Axe of the Wanderer',
    description: 'Its edge bears runes of distant tribes, it hums softly when swung.',
    type: ItemType.WeaponMelee,
    icon: 'assets/items/weapons-melee/axe-wanderer.png',
    baseValue: 540,
    rarity: RarityType.Rare,
    subtype: 'axe',
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    effects: [{ stat: 'damage', value: 6 }],
  },
  {
    id: 'axe-battle',
    name: 'Battle Axe',
    description: 'A good axe can always cut something. A discussion or a head.',
    type: ItemType.WeaponMelee,
    icon: 'assets/items/weapons-melee/axe-battle.png',
    baseValue: 100,
    subtype: 'axe',
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    effects: [{ stat: 'damage', value: 3 }],
    rarity: RarityType.Normal
  },
  {
    id: 'axe-death',
    name: 'Death Axe',
    description: 'It is said that this axe was stolen from death itself. It is also said that it kills you instantly.',
    type: ItemType.WeaponMelee,
    icon: 'assets/items/weapons-melee/axe-death.png',
    baseValue: 2740,
    subtype: 'axe',
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    effects: [{ stat: 'damage', value: 8 }],
    rarity: RarityType.Artefact
  },
  {
    id: 'club',
    name: 'Club',
    description: 'An ordinary club. Well, it\'s made for hitting, quite simply.',
    type: ItemType.WeaponMelee,
    icon: 'assets/items/weapons-melee/club.png',
    baseValue: 270,
    effects: [{ stat: 'damage', value: 1 }],
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    rarity: RarityType.Rare
  },
  {
    id: 'dagger-ceremonial',
    name: 'Ceremonial Dagger',
    description: 'This ceremonial dagger is way too clean. It\'s suspicious.',
    type: ItemType.WeaponMelee,
    icon: 'assets/items/weapons-melee/dagger-ceremonial.png',
    baseValue: 330,
    effects: [{ stat: 'damage', value: 2 }, {stat: 'critical', value: 1}],
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    rarity: RarityType.Normal
  },
  {
    id: 'dagger-damaged',
    name: 'Damaged Dagger',
    description: 'An old, dented dagger, but still sharp enough.',
    type: ItemType.WeaponMelee,
    icon: 'assets/items/weapons-melee/dagger-damaged.png',
    baseValue: 20,
    effects: [{ stat: 'damage', value: 1 }],
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    rarity: RarityType.Normal
  },
  {
    id: 'dagger-epic',
    name: 'Black Dagger',
    description: 'The very presence of this dagger is enough to frighten. In the dark, it would only be seen too late.',
    type: ItemType.WeaponMelee,
    icon: 'assets/items/weapons-melee/dagger-epic.png',
    baseValue: 875,
    effects: [{ stat: 'damage', value: 5 }, {stat: 'attack', value: 1}],
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    rarity: RarityType.Epic
  },
  {
    id: 'dagger-sorcerer',
    name: 'Sorcerer Dagger',
    description: 'Sorcerer daggers come from a time when rituals were legion.',
    type: ItemType.WeaponMelee,
    icon: 'assets/items/weapons-melee/dagger-sorcerer.png',
    baseValue: 1150,
    effects: [{ stat: 'damage', value: 7 }, {stat: 'critical', value: 3}],
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    rarity: RarityType.Legendary
  },
  {
    id: 'dagger-mechanic',
    name: 'Mechanical Dagger',
    description: 'With this mechanical dagger in your pocket, nothing will be able to resist you!',
    type: ItemType.WeaponMelee,
    icon: 'assets/items/weapons-melee/dagger-mechanic.png',
    baseValue: 325,
    effects: [{ stat: 'damage', value: 4 }],
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    rarity: RarityType.Rare
  },
  {
    id: 'hammer',
    name: 'Hammer',
    description: 'A big, heavy hammer. As long as you don\'t hit your fingers with it, everything\'s fine.',
    type: ItemType.WeaponMelee,
    icon: 'assets/items/weapons-melee/hammer.png',
    baseValue: 430,
    effects: [{ stat: 'damage', value: 4 }],
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    twoHanded: true,
    rarity: RarityType.Normal
  },
  {
    id: 'hammer-epic',
    name: 'Sacred Hammer',
    description: 'This hammer looks so imposing and yet it\'s so light. You just have to let yourself be guided.',
    type: ItemType.WeaponMelee,
    icon: 'assets/items/weapons-melee/hammer-epic.png',
    baseValue: 980,
    effects: [{ stat: 'damage', value: 15 }],
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    twoHanded: true,
    rarity: RarityType.Epic
  },
  {
    id: 'hammer-soul',
    name: 'Smith\'s Soul Hammer',
    description: 'It vibrates faintly, as if remembering the blows that forged it.',
    type: ItemType.WeaponMelee,
    icon: 'assets/items/weapons-melee/hammer-soul.png',
    baseValue: 560,
    rarity: RarityType.Rare,
    subtype: 'hammer',
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    twoHanded: true,
    effects: [{ stat: 'damage', value: 10 }, { stat: 'tool', value: 1 }],
  },
  {
    id: 'sword-bastard',
    name: 'Bastard Sword',
    description: 'Between a short sword and a long sword, it suits those who want a happy medium.',
    type: ItemType.WeaponMelee,
    icon: 'assets/items/weapons-melee/sword-bastard.png',
    baseValue: 110,
    effects: [{ stat: 'damage', value: 4 }],
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    rarity: RarityType.Normal
  },
  {
    id: 'sword-ignition',
    name: 'Sword of Ignition',
    description: 'An elemental sword. Very few of these have been found in this world.',
    type: ItemType.WeaponMelee,
    icon: 'assets/items/weapons-melee/sword-ignition.png',
    baseValue: 2350,
    effects: [{ stat: 'damage', value: 7 }, {stat: 'burn', value: 4}],
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    rarity: RarityType.Artefact
  },
  {
    id: 'sword-long',
    name: 'Long Sword',
    description: 'This sword requires some training. But once mastered, it wreaks havoc.',
    type: ItemType.WeaponMelee,
    icon: 'assets/items/weapons-melee/sword-long.png',
    baseValue: 150,
    effects: [{ stat: 'damage', value: 5 }],
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    rarity: RarityType.Normal
  },
  {
    id: 'sword-mechanic',
    name: 'Mechanical Sword',
    description: 'This mechanical sword still works, you can hear it whirring and your hand almost trembles.',
    type: ItemType.WeaponMelee,
    icon: 'assets/items/weapons-melee/sword-mechanic.png',
    baseValue: 450,
    effects: [{ stat: 'damage', value: 5 }],
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    rarity: RarityType.Rare
  },
  {
    id: 'sword-short',
    name: 'Short Sword',
    description: 'A short sword at your side can always be useful.',
    type: ItemType.WeaponMelee,
    icon: 'assets/items/weapons-melee/sword-short.png',
    baseValue: 90,
    effects: [{ stat: 'damage', value: 3 }],
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    rarity: RarityType.Normal
  },
  {
    id: 'sword-embers',
    name: 'Sword of Embers',
    description: 'A faint orange glow dances along the blade, warm to the touch.',
    type: ItemType.WeaponMelee,
    icon: 'assets/items/weapons-melee/sword-embers.png',
    baseValue: 505,
    rarity: RarityType.Rare,
    subtype: 'sword',
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    effects: [{ stat: 'damage', value: 6 }, { stat: 'burn', value: 1 }],
  },
  {
    id: 'sword-rare',
    name: 'Rare Sword',
    description: 'A sword of rather rare quality, perfectly balanced.',
    type: ItemType.WeaponMelee,
    icon: 'assets/items/weapons-melee/sword-embers.png',
    baseValue: 250,
    rarity: RarityType.Rare,
    subtype: 'sword',
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    effects: [{ stat: 'damage', value: 5 }],
  },
  {
    id: 'saber',
    name: 'Saber',
    description: 'This is a very sharp saber, we will have to test it to verify that.',
    type: ItemType.WeaponMelee,
    icon: 'assets/items/weapons-melee/saber.png',
    baseValue: 90,
    effects: [{ stat: 'damage', value: 3 }],
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    rarity: RarityType.Normal
  },
  {
    id: 'spear',
    name: 'Spear',
    description: 'It\'s always a pleasure to be able to impale an enemy. It\'s messy, sure, but enjoyable.',
    type: ItemType.WeaponMelee,
    icon: 'assets/items/weapons-melee/spear.png',
    baseValue: 210,
    effects: [{ stat: 'damage', value: 7 }],
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    twoHanded: true,
    rarity: RarityType.Normal
  },
  {
    id: 'staff-fighting',
    name: 'Fight Staff',
    description: 'Those who know how to handle batons can knock you out faster than you think.',
    type: ItemType.WeaponMelee,
    icon: 'assets/items/weapons-melee/staff-fighting.png',
    baseValue: 180,
    effects: [{ stat: 'damage', value: 4 }],
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    twoHanded: true,
    rarity: RarityType.Normal
  },
  {
    id: 'sword-epic',
    name: 'Rune Sword',
    description: 'Once the magic is released from this sword, the fight is no longer the same.',
    type: ItemType.WeaponMelee,
    icon: 'assets/items/weapons-melee/sword-epic.png',
    baseValue: 850,
    effects: [{ stat: 'damage', value: 7 }],
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    rarity: RarityType.Epic
  },
  {
    id: 'wrench',
    name: 'Wrench',
    description: 'The advantage of these keys is that they are just as useful for beating monsters as they are for repairing things.',
    type: ItemType.WeaponMelee,
    icon: 'assets/items/weapons-melee/sword-epic.png',
    baseValue: 150,
    effects: [{ stat: 'damage', value: 15 }, { stat: 'tool', value: 2 }],
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    rarity: RarityType.Normal
  },
];

export const WEAPON_RANGE_ITEMS: Item[] = [
  {
    id: 'blunderbuss',
    name: 'Blunderbuss',
    description: 'A blunderbuss from the Old War, still functional it seems!',
    type: ItemType.WeaponRange,
    icon: 'assets/items/weapons-range/blunderbuss.png',
    baseValue: 325,
    subtype: 'bow',
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    rarity: RarityType.Rare,
    effects: [{ stat: 'damage', value: 4 }]
  },
  {
    id: 'bow-golden',
    name: 'Golden Bow',
    description: 'A golden bow, made of precious wood and decorated with ancient runes.',
    type: ItemType.WeaponRange,
    icon: 'assets/items/weapons-range/bow-golden.png',
    baseValue: 650,
    subtype: 'bow',
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    twoHanded: true,
    rarity: RarityType.Epic,
    effects: [{ stat: 'damage', value: 4 }]
  },
  {
    id: 'bow-eagle',
    name: 'The Eagles\' Bow',
    description: 'The Eagle Bow is a powerful item; its arrows are deadly and dive towards you.',
    type: ItemType.WeaponRange,
    icon: 'assets/items/weapons-range/bow-eagle.png',
    baseValue: 2400,
    subtype: 'bow',
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    twoHanded: true,
    rarity: RarityType.Artefact,
    effects: [{ stat: 'damage', value: 10 }]
  },
  {
    id: 'bow-long',
    name: 'Long Bow',
    description: 'A long, flexible, and beautifully crafted bow.',
    type: ItemType.WeaponRange,
    icon: 'assets/items/weapons-range/bow-long.png',
    baseValue: 220,
    subtype: 'bow',
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    twoHanded: true,
    rarity: RarityType.Normal,
    effects: [{ stat: 'damage', value: 4 }]
  },
  {
    id: 'bow-short',
    name: 'Short Bow',
    description: 'A short bow. Simple but effective for those who know how to handle it.',
    type: ItemType.WeaponRange,
    icon: 'assets/items/weapons-range/bow-short.png',
    baseValue: 80,
    subtype: 'bow',
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    twoHanded: true,
    rarity: RarityType.Normal,
    effects: [{ stat: 'damage', value: 2 }]
  },
  {
    id: 'bow-whisper',
    name: 'Bow of Whispering Winds',
    description: 'The bowstring sings with the sound of wind when drawn.',
    type: ItemType.WeaponRange,
    icon: 'assets/items/weapons-range/bow-whisper.png',
    baseValue: 900,
    rarity: RarityType.Legendary,
    subtype: 'bow',
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    twoHanded: true,
    effects: [{ stat: 'damage', value: 6 }, { stat: 'critical', value: 5 }],
  },
  {
    id: 'crossbow',
    name: 'Crossbow',
    description: 'A simple crossbow, but when handled well, it can do some damage!',
    type: ItemType.WeaponRange,
    icon: 'assets/items/weapons-range/crossbow.png',
    baseValue: 90,
    rarity: RarityType.Normal,
    subtype: 'bow',
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    twoHanded: true,
    effects: [{ stat: 'damage', value: 3 }],
  },
  {
    id: 'crossbow-mechanic',
    name: 'Mechanical Crossbow',
    description: 'When this crossbow is cocked, the sound it makes is a sign that you should take cover.',
    type: ItemType.WeaponRange,
    icon: 'assets/items/weapons-range/crossbow-mechanic.png',
    baseValue: 240,
    rarity: RarityType.Rare,
    subtype: 'bow',
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    twoHanded: true,
    effects: [{ stat: 'damage', value: 5 }],
  },
  {
    id: 'scepter-crystal',
    name: 'Crystal Scepter',
    description: 'A crystal scepter that sends out shocks, at height it does damage.',
    type: ItemType.WeaponRange,
    icon: 'assets/items/weapons-range/scepter-crystal.png',
    baseValue: 90,
    rarity: RarityType.Normal,
    subtype: 'bow',
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    effects: [{ stat: 'damage', value: 3 }],
  },
  {
    id: 'staff-souls',
    name: 'Staff of Souls',
    description: 'A staff of Souls, all it wants is to feed.',
    type: ItemType.WeaponRange,
    icon: 'assets/items/weapons-range/staff-souls.png',
    baseValue: 280,
    rarity: RarityType.Rare,
    subtype: 'bow',
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    twoHanded: true,
    effects: [{ stat: 'damage', value: 5 }],
  },
  {
    id: 'staff-spider',
    name: 'Staff of spiders',
    description: 'The spiders that escape from this stick can quickly overwhelm you!',
    type: ItemType.WeaponRange,
    icon: 'assets/items/weapons-range/staff-spider.png',
    baseValue: 350,
    rarity: RarityType.Rare,
    subtype: 'bow',
    equipSlot: [EquipSlot.Weapon1, EquipSlot.Weapon2],
    twoHanded: true,
    effects: [{ stat: 'damage', value: 6 }],
  },
];

export const BASE_ITEMS: Item[] = [
  ...ACCESSORY_ITEMS,
  ...ARMOR_ITEMS,
  ...CONSUMABLE_ITEMS,
  ...RESOURCE_ITEMS,
  ...UTILITY_ITEMS,
  ...WEAPON_MELEE_ITEMS,
  ...WEAPON_RANGE_ITEMS
];

